name: xylophone
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0" # Updated Dart SDK version

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5 # Updated version
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/